# Generated by Django 5.2.4 on 2025-07-22 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("card_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("supertype", models.CharField(max_length=50)),
                ("subtypes", models.JSONField(blank=True, null=True)),
                ("hp", models.CharField(blank=True, max_length=10, null=True)),
                ("types", models.JSONField(blank=True, null=True)),
                ("evolves_to", models.JSONField(blank=True, null=True)),
                ("rules", models.JSONField(blank=True, null=True)),
                ("retreat_cost", models.JSONField(blank=True, null=True)),
                ("converted_retreat_cost", models.IntegerField(blank=True, null=True)),
                ("number", models.CharField(max_length=10)),
                ("artist", models.CharField(blank=True, max_length=100, null=True)),
                ("rarity", models.CharField(blank=True, max_length=50, null=True)),
                ("national_pokedex_numbers", models.JSONField(blank=True, null=True)),
                ("small_image", models.URLField(blank=True, null=True)),
                ("large_image", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="CardSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("set_id", models.CharField(max_length=50, unique=True)),
                ("name", models.CharField(max_length=100)),
                ("series", models.CharField(max_length=100)),
                ("printed_total", models.IntegerField()),
                ("total", models.IntegerField()),
                ("ptcgo_code", models.CharField(blank=True, max_length=20, null=True)),
                ("release_date", models.DateField()),
                ("updated_at", models.DateTimeField()),
                ("symbol_image", models.URLField()),
                ("logo_image", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Attack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("cost", models.JSONField(blank=True, null=True)),
                ("converted_energy_cost", models.IntegerField()),
                ("damage", models.CharField(max_length=20)),
                ("text", models.TextField(blank=True, null=True)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attacks",
                        to="cards.card",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="card",
            name="set",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cards",
                to="cards.cardset",
            ),
        ),
        migrations.CreateModel(
            name="TCGPlayerPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("updated_at", models.DateField()),
                ("low", models.FloatField(blank=True, null=True)),
                ("mid", models.FloatField(blank=True, null=True)),
                ("high", models.FloatField(blank=True, null=True)),
                ("market", models.FloatField(blank=True, null=True)),
                ("direct_low", models.FloatField(blank=True, null=True)),
                (
                    "card",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tcgplayer_price",
                        to="cards.card",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Weakness",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=50)),
                ("value", models.CharField(max_length=10)),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weaknesses",
                        to="cards.card",
                    ),
                ),
            ],
        ),
    ]
