# Generated by Django 5.2.4 on 2025-07-23 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=50, unique=True)),
                ('discovered_at', models.DateTimeField(auto_now_add=True)),
                ('error', models.BooleanField(default=False)),
                ('last_checked', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
