# Generated by Django 5.2.4 on 2025-07-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_cardref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardset',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
